### PR TITLE
Fixing 'Aussie-rules' spacing

### PR DESCRIPTION
**Pull request by jbogard**
From 2 to 4 like the rest of the world uses

### CODE REVIEW

**Comment by robashton** [comment]
GitHub is not a place for humour

**Comment by thejoker3000** [comment]
This PR has been denied

**Comment by danjagnow** [comment]
How about adding an [.editorconfig file](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) to make the conventions stick?

**Comment by jbogard** [comment]
@danjagnow well that's no fun at all!

**Comment by mdawsonuk** [comment]
@jbogard Might wanna fix the merge conflict 😁

**Comment by robashton** [comment]
Heavens, asking an earnest *contributor* to perform extra work on top of their initial pull request??! This is not how you build a community people

**Comment by troyhunt** [comment]
> How about adding an [.editorconfig file](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019) to make the conventions stick?

Do it 😎

**Pull request closed without merging**
