### PR TITLE
Add tests #2

### PR DESCRIPTION
**Pull request by martins-vds**
Copy of #35 

This PR adds tests and makes small refactors

### CODE REVIEW

**Comment by martins-vds** [comment]
@stebet , could you take a look at this PR?

**Comment by mdawsonuk** [comment]
Looks good to me - my only suggestion would be some documentation on the helper classes just to clarify their roles

**Comment by martins-vds** [comment]
> This is looking good as well. Can you fix the nullable warnings @martins-vds?

For sure

**Comment by stebet** [comment]
I'm going to merge this as is along with more PRs and follow up with a cleanup PR later.

**Pull request merged**
