### PR TITLE
Refactor to .NET 5

### PR DESCRIPTION
**Pull request by martins-vds**
This PR: 
- Refactors the code Azure Functions v3 using .NET 5
- Adds Dependency injection.
- Adds tests
- Incorporates changes from #19 and #10

### CODE REVIEW

**Comment by issafram** [comment]
might be best to wait for .NET 6 to be released which I believe is soon.  It is a LTS release.

**Comment by stebet** [comment]
Or 3.1 as it's the current LTS release, also 5.0 is still in preview on Azure Functions.

**Comment by mdawsonuk** [comment]
There's gonna be a lot of work that will stay on .Net Framework 4.6.2 for the moment, it might be wise to close this PR and return to it once the project is more stable and migration to .Net Core 3.1 is more feasible (let's not have production on previews 😁)

**Comment by martins-vds** [comment]
> Or 3.1 as it's the current LTS release, also 5.0 is still in preview on Azure Functions.

Actually, Azure Function support for .net 5.0 has already reached GA: [https://azure.microsoft.com/en-ca/updates/general-availability-azure-functions-supports-net-5-in-production/](https://azure.microsoft.com/en-ca/updates/general-availability-azure-functions-supports-net-5-in-production/)

**Comment by martins-vds** [comment]
> Or 3.1 as it's the current LTS release, also 5.0 is still in preview on Azure Functions.

I would suggest doing the migration to .net core 3.1 as soon as possible even before starting new development on .net framework 4.6.2. This way we can leverage Azure Functions V3 instead of V1 and it would make a future migration to .NET 6 way easier

**Comment by martins-vds** [comment]
I'll submit another PR refactoring the code to .net core 3.1 so you guys can compare and contrast to .net framework 4.6.1 and then decide whether or not to merge it.

**Review by antgray80 — APPROVED** [review]

**Comment by slang25** [comment]
@martins-vds as you say, .NET 5 support is GA, this change looks good 👍

**Comment by stebet** [comment]
Would it be a good idea if we split this PR up into smaller parts as it's quite big and does multiple things making it a bit hard to review?

It's doing quite a lot as is:
* .editconfig settings
* Framework upgrades
* Adds lots of tests
* Interface abstractions
* Readme changes

For me personally at least, smaller, more isolated PRs are easier to review and grasp :)

**Comment by troyhunt** [comment]
> For me personally at least, smaller, more isolated PRs are easier to review and grasp :)

+1 👆

**Comment by mdawsonuk** [comment]
This PR is mostly obsolete now that #21 has been merged

**Comment by martins-vds** [comment]
> This PR is mostly obsolete now that #21 has been merged

How so? The changes made by #21 only upgraded the code to .net core 3.1. This PR is doing much more. Take a look at the description :)

**Comment by mdawsonuk** [comment]
> How so? The changes made by #21 only upgraded the code to .net core 3.1. This PR is doing much more. Take a look at the description :)

Ah okay, now that I've had a better look at what you've done I'd recommend - like stebet and troy suggested  - splitting this up into smaller PRs which can be scrutinised and merged individually.  And rather than merging from the main branch on this repository, you appear to have merged individual pull requests from forked repos? This doesn't seem like good practice.

However, I'm really keen to see your tests integrated - this is stuff I could do with for the work on my PR.

**Comment by tomkerkhove** [comment]
This can be closed in favor of #27

**Comment by stebet** [comment]
It'd be great to get the tests from this PR into the existing codebase.

**Comment by martins-vds** [comment]
@stebet , I'll be doing this today :)

**Comment by martins-vds** [comment]
In fact, I will wait until #29 gets merged so I don't need to do a lot of refactoring.

**Comment by martins-vds** [comment]
> This can be closed in favor of #27

Once #35 and #36 are merged, I'll close this PR.

**Pull request closed without merging**
