### PR TITLE
Upgrade to .NET 5

### PR DESCRIPTION
**Pull request by martins-vds**
This smaller PR is related to #16 and only makes minimal changes to the code to enable support for .NET 5.

### CODE REVIEW

**Comment by mdawsonuk** [comment]
Looks good 👍🏻

**Comment by LanceMcCarthy** [comment]
I actually did the same and then realized you already had a PR open for it :D  I concur, the implementation looks good.

**Comment by issafram** [comment]
We should really wait for .NET 6.  Currently .NET Core 3.1 is LTS.  .NET 5 isn't.

**Comment by funkysi1701** [comment]
> We should really wait for .NET 6. Currently .NET Core 3.1 is LTS. .NET 5 isn't.

Why is this a problem? Upgrade to .NET 5 now and upgrade to .NET 6 in November?

**Comment by troyhunt** [comment]
> Why is this a problem? Upgrade to .NET 5 now and upgrade to .NET 6 in November?

Agreed, merging.

@martins-vds - thanks for this, hope it helps break #pr16 into smaller units.

**Comment by mdawsonuk** [comment]
@martins-vds I'm getting this error when running my Functions locally after merging your branch into my PR `Microsoft.Azure.WebJobs.Extensions.FunctionMetadataLoader: At least one binding must be declared` - any idea why? I've got both QueueTriggers and TimerTriggers

**Pull request merged**
